.eqv SYSCALL_PRINT_INT 1
.eqv SYSCALL_PRINT_STRING 4
.eqv SYSCALL_PRINT_CHAR 11
.eqv SYSCALL_PRINT_HEX 34

.eqv SYSCALL_READ_INT 5
.eqv SYSCALL_READ_FLOAT 6
.eqv SYSCALL_READ_CHAR 12

.eqv SYSCALL_RND_RANGE 42

.eqv SYSCALL_EXIT 17

# vim: ft=asm
